### ISSUE TITLE
[BUG] missed liquidations on goerli

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#187] opened 2023-03-30 10:19 UTC
Running v0.10.0, the sentinel seems to have overlooked a few insolvent streams on Goerli.
On of the was https://console.superfluid.finance/goerli/streams/0x3577eb2f0e0a74dc95ebde2ce7e33da739db9cfe-0x0dfff175e45c12a12af97259adb34038634f40c2-0x8ae68021f6170e5a766be613cea0d75236ecca9a-0.0

Restarting didn't help, restarting from snapshot didn't help.
Restarting from scratch (not using a snapshot) finally fixed it ([closing tx](https://goerli.etherscan.io/tx/0x6fbc47b0a5d8f845f366430182cf8c07c937d25b8e92a2f36abf47f99ddd0022)).

So the most likely reason seems to be an issue with the snapshot.
This is the snapshot: https://cloudflare-ipfs.com/ipfs/Qmbpqqpj56gqVEvtCq32dHLzHMoVQMsFQem5KnsJdndtQT

In case it matters, there's also a copy of the sqlite file synced from snapshot until 2023.03.29 (stream already insolvent, not yet closed, not seen by the sentinel).

**Comment by ngmachado** [comment] 2023-03-30 13:42
In this case, it seems that the snapshot may have been the root cause of the issue with the insolvent streams on Goerli.

Moving forward, it may be a good idea to review the snapshot creation process and ensure that it is thoroughly tested before sharing it publicly. 

The process could be generating two snapshots from different sources and compare it.

**Comment by ngmachado** [comment] 2023-10-11 12:51
This didn't move, going to close it

**Closed by ngmachado** 2023-10-11 12:51 UTC
Labels: Type: Bug
